export const START_ROUND_CLICKED = 'START_ROUND_CLICKED';
export const PLAYER_ADDED = 'PLAYER_ADDED';
export const COURSE_CLICKED = 'COURSE_CLICKED';
export const COURSE_BASKETS_REMOVE = 'COURSE_BASKETS_REMOVE';

export const COURSE_BASKETS_SET = 'COURSE_BASKETS_SET';
export const SCORE_MARKED = 'SCORE_MARKED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
